Repository VemundFredriksen/TDT4290-Theia, pull requests merged in 2019-11, with the labels that each got.

#111 Feat/sprint4 98/who is resposible
  dockerexpressmongo/app.js
  dockerexpressmongo/models/Area.js
  dockerexpressmongo/package-lock.json
  dockerexpressmongo/package.json
  dockerexpressmongo/routes/api/areaAPI.js
Labels: backend

#113 Update detected object schemas
  dockerexpressmongo/models/Object.js
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#117 Feat/sprint4 102/previous values of objects
  dockerexpressmongo/models/Object.js
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#128 objects will be stored with bounding-box data
  dockerexpressmongo/models/Object.js
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#131 Feat/sprint4 118/delete all objects
  dockerexpressmongo/routes/api/areaAPI.js
  dockerexpressmongo/routes/api/objectsAPI.js
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#140 Updated insert-objectdata methode
  cvmodule/utilities/BBox_tool.py
  cvmodule/utilities/crop_every_box_inside.py
  dockerexpressmongo/models/Area.js
  dockerexpressmongo/models/Object.js
  dockerexpressmongo/routes/api/areaAPI.js
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#144 Feat/sprint4 143/workorders as csv
  dockerexpressmongo/models/Area.js
  dockerexpressmongo/models/Object.js
  dockerexpressmongo/models/Workorder.js
  dockerexpressmongo/package-lock.json
  dockerexpressmongo/package.json
  dockerexpressmongo/routes/api/objectsAPI.js
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#146 uri fix
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#145 Added auth endpoint to objectsAPI.js
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#149 Feat/sprint4 143/workorders as csv
  dockerexpressmongo/routes/api/objectsAPI.js
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#150 Feat/sprint4 143/workorders as csv
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#151 updated all delete methodes in workorderAPI. Also overall cleaning
  dockerexpressmongo/package-lock.json
  dockerexpressmongo/package.json
  dockerexpressmongo/routes/api/areaAPI.js
  dockerexpressmongo/routes/api/objectsAPI.js
  dockerexpressmongo/routes/api/workorderAPI.js
Labels: backend

#152 get -> post when body in use
  dockerexpressmongo/routes/api/objectsAPI.js
Labels: backend

#155 uploading now works, needs code cleanup tho
  cvmodule/Server/Client.py
  cvmodule/Server/RequestHandler.py
  cvmodule/core/darknet/Makefile
  cvmodule/core/video_analysis.py
  cvmodule/core/video_converter.py
Labels: bug

#147 Feat/sprint4 142/draw boxes around potholes
  webapp/src/components/infoBar/InfoBar.js
  webapp/src/pages/HomePage.js
Labels: frontend
